-- ============================================================
-- QTAC Data Engineer Assessment
-- Script: 04_load_courses.sql
-- Purpose:
--   Load courses.csv into dim_course.
--
-- Model context:
--   dim_course is a descriptive dimension table.
--   It provides course and institution context for the
--   preference / offer fact table.
--
-- Source:
--   source_data/courses.csv
--
-- Target:
--   dim_course
--
-- Key transformations:
--   - Generate course_key as a warehouse surrogate key
--   - Standardise study_mode casing
--   - Convert csp_available from Y/N to BOOLEAN
--   - Convert active_flag from 1/0 to BOOLEAN
--   - Preserve missing atar_cutoff values as NULL
-- ============================================================


-- ============================================================
-- Load course dimension
-- ============================================================
-- Grain:
--   One row per course.
--
-- Key design:
--   course_key is generated by the warehouse.
--   course_code is retained as the natural/source key from the
--   source file.
--
-- Data quality handling:
--   Profiling showed inconsistent study_mode casing, with both
--   'Full-time' and 'full-time' present in the source data.
--   This load standardises those values into consistent labels.
--
--   Source flags are converted into BOOLEAN values to make the
--   warehouse easier to query and report from.
-- ============================================================

INSERT INTO dim_course (
    course_key,
    course_code,
    course_name,
    institution_code,
    institution_name,
    campus,
    study_mode,
    duration_years,
    atar_cutoff,
    csp_available,
    active_flag
)
SELECT
    -- Generate a warehouse surrogate key for each course.
    ROW_NUMBER() OVER (ORDER BY course_code) AS course_key,

    -- Retain the source course identifier for traceability.
    course_code,

    course_name,
    institution_code,
    institution_name,
    campus,

    -- Standardise inconsistent source casing:
    -- 'Full-time' and 'full-time' should be treated as the same value.
    CASE
        WHEN LOWER(study_mode) = 'full-time' THEN 'Full-time'
        WHEN LOWER(study_mode) = 'part-time' THEN 'Part-time'
        ELSE study_mode
    END AS study_mode,

    duration_years,

    -- atar_cutoff is nullable because profiling identified one
    -- missing value in the course source file.
    atar_cutoff,

    -- Convert source Y/N flag into a BOOLEAN value.
    CASE
        WHEN csp_available = 'Y' THEN TRUE
        WHEN csp_available = 'N' THEN FALSE
        ELSE NULL
    END AS csp_available,

    -- Convert source 1/0 flag into a BOOLEAN value.
    CASE
        WHEN active_flag = 1 THEN TRUE
        WHEN active_flag = 0 THEN FALSE
        ELSE NULL
    END AS active_flag

FROM read_csv_auto('source_data/courses.csv');


-- ============================================================
-- Validation checks
-- ============================================================
-- Expected results:
--   dim_course row count = 14
--
--   study_mode should only contain standardised values:
--     Full-time
--     Part-time
--
--   csp_available and active_flag should be BOOLEAN values.
-- ============================================================

SELECT COUNT(*) AS course_count
FROM dim_course;

SELECT
    study_mode,
    COUNT(*) AS row_count
FROM dim_course
GROUP BY study_mode
ORDER BY study_mode;

SELECT
    csp_available,
    active_flag,
    COUNT(*) AS row_count
FROM dim_course
GROUP BY csp_available, active_flag
ORDER BY csp_available, active_flag;

SELECT *
FROM dim_course
ORDER BY course_key;