-- ============================================================
-- QTAC Data Engineer Assessment
-- Script: 05_load_qualifications.sql
-- Purpose:
--   Load qualifications.csv into dim_qualification.
--
-- Model context:
--   dim_qualification is a descriptive dimension table.
--   It provides applicant qualification context for reporting,
--   including qualification type, GPA, ATAR score, and whether
--   the qualification has been verified.
--
-- Source:
--   source_data/qualifications.csv
--
-- Target:
--   dim_qualification
--
-- Key transformations:
--   - Generate qualification_key as a warehouse surrogate key
--   - Keep qualification_id as the source/natural key
--   - Keep applicant_id as the link back to the applicant
--   - Convert verified from Y/N to BOOLEAN
--   - Convert text 'NULL' values into real SQL NULLs
--   - Safely cast GPA and ATAR values to DOUBLE
-- ============================================================


-- ============================================================
-- Load qualification dimension
-- ============================================================
-- Grain:
--   One row per applicant qualification.
--
-- Key design:
--   qualification_key is generated by the warehouse.
--   qualification_id is retained as the natural/source key from
--   the qualifications extract.
--
-- Relationship design:
--   applicant_id is retained to link qualifications back to the
--   source applicant identity.
--
--   I have not linked dim_qualification directly to applicant_key
--   because dim_applicant is SCD Type 2. Linking qualifications to
--   a specific applicant_key would require deciding which historical
--   applicant version each qualification belongs to. For this
--   assessment, applicant_id is a simpler and clearer relationship.
--
-- Data quality handling:
--   Profiling showed GPA and ATAR contain missing/null-like values.
--   Some of these appear as the literal text 'NULL' in the CSV, so
--   NULLIF is used to convert the text value into a real SQL NULL.
--
--   TRY_CAST is used so invalid numeric values do not fail the
--   entire load. If a value cannot be converted to DOUBLE, it will
--   become NULL.
--
--   verified is converted from the source Y/N flag into a BOOLEAN
--   value for cleaner reporting.
-- ============================================================

INSERT INTO dim_qualification (
    qualification_key,
    qualification_id,
    applicant_id,
    qualification_type,
    institution_name,
    year_completed,
    gpa,
    atar_score,
    verified
)
SELECT
    -- Generate a warehouse surrogate key for each qualification.
    ROW_NUMBER() OVER (ORDER BY qualification_id) AS qualification_key,

    -- Retain the source qualification identifier for traceability.
    qualification_id,

    -- Keep applicant_id as the source-level relationship back to applicants.
    applicant_id,

    qualification_type,
    institution_name,
    year_completed,

    -- Convert literal text 'NULL' into real SQL NULL, then safely cast.
    TRY_CAST(NULLIF(gpa, 'NULL') AS DOUBLE) AS gpa,
    TRY_CAST(NULLIF(atar_score, 'NULL') AS DOUBLE) AS atar_score,

    -- Convert source Y/N flag into a BOOLEAN value.
    CASE
        WHEN verified = 'Y' THEN TRUE
        WHEN verified = 'N' THEN FALSE
        ELSE NULL
    END AS verified

FROM read_csv_auto('source_data/qualifications.csv');


-- ============================================================
-- Validation checks
-- ============================================================
-- Expected results:
--   dim_qualification row count = 17
--
--   verified should be converted into BOOLEAN values.
--
--   The orphan check is included because profiling identified one
--   qualification record for applicant_id 9999 that does not exist
--   in dim_applicant.
--
--   For this assessment, the orphan qualification is retained for
--   source traceability and documented as a data quality issue.
-- ============================================================

SELECT COUNT(*) AS qualification_count
FROM dim_qualification;

SELECT
    verified,
    COUNT(*) AS row_count
FROM dim_qualification
GROUP BY verified
ORDER BY verified;

-- Check for qualification records that do not have a matching applicant.
SELECT q.*
FROM dim_qualification q
LEFT JOIN dim_applicant a
    ON q.applicant_id = a.applicant_id
WHERE a.applicant_id IS NULL;