-- ============================================================
-- QTAC Data Engineer Assessment
-- Script: 06_load_preferences.sql
-- Purpose:
--   Load preferences.csv into fact_preference.
--
-- Model context:
--   fact_preference is the central fact table in the Kimball model.
--   It represents the core business event:
--   an applicant selects a course preference, may receive an offer,
--   and may respond to that offer.
--
-- Source:
--   source_data/preferences.csv
--
-- Target:
--   fact_preference
--
-- Key transformations:
--   - Generate preference_key as a warehouse surrogate key
--   - Keep preference_id as the source/natural key
--   - Join to dim_applicant to get applicant_key
--   - Join to dim_course to get course_key
--   - Retain applicant_id and course_code for source traceability
--   - Safely cast offer and response dates
-- ============================================================


-- ============================================================
-- Load preference fact table
-- ============================================================
-- Grain:
--   One row per applicant course preference.
--
-- Key design:
--   preference_key is generated by the warehouse.
--   preference_id is retained as the natural/source key from
--   preferences.csv.
--
-- Relationship design:
--   applicant_key links the fact to dim_applicant.
--   course_key links the fact to dim_course.
--
-- Source traceability:
--   applicant_id and course_code are also retained in the fact
--   table. These make it easier to audit the warehouse row back to
--   the source extract.
--
-- SCD2 design choice:
--   dim_applicant is an SCD Type 2 table, meaning one applicant_id
--   can have multiple applicant_key values over time.
--
--   For this assessment, preferences are linked to the current
--   applicant record using a.is_current = TRUE.
--
--   In a production point-in-time model, the fact could instead
--   be linked to the applicant version that was valid at the
--   application, offer, or response date.
--
-- Date handling:
--   Some source date values may appear as the literal text 'NULL'.
--   NULLIF converts this text into a real SQL NULL.
--   TRY_CAST then safely converts valid values into DATE.
-- ============================================================

INSERT INTO fact_preference (
    preference_key,
    preference_id,
    applicant_key,
    course_key,
    applicant_id,
    course_code,
    preference_order,
    application_year,
    offer_status,
    offer_date,
    response,
    response_date
)
SELECT
    -- Generate a warehouse surrogate key for each preference row.
    ROW_NUMBER() OVER (ORDER BY p.preference_id) AS preference_key,

    -- Retain the source preference identifier for traceability.
    p.preference_id,

    -- Warehouse foreign keys from the related dimensions.
    a.applicant_key,
    c.course_key,

    -- Retain source identifiers to make the fact table auditable.
    p.applicant_id,
    p.course_code,

    -- Business event fields from the preference source extract.
    p.preference_order,
    p.application_year,
    p.offer_status,

    -- Convert literal text 'NULL' into real SQL NULL, then safely cast.
    TRY_CAST(NULLIF(p.offer_date, 'NULL') AS DATE) AS offer_date,

    p.response,

    -- Convert literal text 'NULL' into real SQL NULL, then safely cast.
    TRY_CAST(NULLIF(p.response_date, 'NULL') AS DATE) AS response_date

FROM read_csv_auto('source_data/preferences.csv') p

-- Join to the current applicant dimension record.
-- This avoids duplicating fact rows where an applicant has multiple
-- SCD2 versions.
INNER JOIN dim_applicant a
    ON p.applicant_id = a.applicant_id
   AND a.is_current = TRUE

-- Join to the course dimension to obtain course_key.
INNER JOIN dim_course c
    ON p.course_code = c.course_code;


-- ============================================================
-- Validation checks
-- ============================================================
-- Expected results:
--   fact_preference row count = 22
--
--   Accepted response rows = 12
--
--   Applicant 1002 has two accepted rows in the fact table.
--   These are retained for source traceability and handled later
--   in the gold layer by ranking accepted offers.
--
--   rows_with_missing_applicant_or_course should be 0 because all
--   loaded preference records should have valid applicant and course
--   dimension keys.
-- ============================================================

SELECT COUNT(*) AS preference_count
FROM fact_preference;

SELECT
    preference_id,
    applicant_id,
    course_code,
    preference_order,
    offer_status,
    response
FROM fact_preference
WHERE response = 'Accepted'
ORDER BY applicant_id, preference_order;

SELECT
    COUNT(*) AS rows_with_missing_applicant_or_course
FROM fact_preference
WHERE applicant_key IS NULL
   OR course_key IS NULL;